version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    networks:
      - security-network
    env_file:
    - .env

  event-service:
    build: ./event-service
    ports:
      - "8001:8001"
    networks:
      - security-network
    env_file:
    - .env

  alert-service:
    build: ./alert-service
    ports:
      - "8002:8002"
    networks:
      - security-network
    env_file:
    - .env
networks:
  security-network: